taglist = """
ccrogues
 Load tags
52 (1)
fanart (383)
axel walker (144)
lisa snart (468)
tv: legends of tomorrow (1510)
mick rory (1290)
lot 3x12 (20)
pairing: vixenwave (70)
lot 3x11 (17)
pairing: atomwave (131)
lot 3x05 (19)
lot spoilers (189)
lot 3x14 (5)
pairing: roraz (7)
tv: the flash (1128)
the flash 1x04 (59)
leonard snart (1886)
earth x leonard snart (155)
lot 3x10 (54)
pairing: coldray (38)
comicedit (12)
dcedit (17)
dcmultiverse (10)
jamesjesseedit (4)
james jesse (94)
trickster (1)
comics (622)
graphic (139)
c: the flash v1 (70)
c: the flash v2 (90)
ccr1k (38)
comics10 (4)
*edit (8)
* (380)
by meghan (179)
pairing: coldstantine (11)
new 52 (161)
c: the flash v4 (118)
roscoe hynes (2)
leonard snart death / (48)
lot 1x15 (74)
pairing: coldwave (318)
food / (58)
Anonymous (12)
asks (19)
homophobia / (7)
theflashedit (96)
rosadillonedit (9)
rosa dillon (62)
dctvladies (11)
dailydctv (14)
dcladies (4)
the flash 3x04 (34)
the flash 3x19 (20)
dctv10 (4)
*gifs (161)
pairing: coldflash (238)
lot 1x16 (32)
the flash 3x10 (3)
ableism / (23)
lot 1x11 (31)
lot 1x06 (34)
alcohol / (149)
moodboard (314)
c: the flash v5 (61)
c: suicide squad most wanted: el diablo and boomerang (2)
digger harkness (240)
pairing: captain canary (164)
jltfpedit (1)
dcauedit (7)
sam scudder (141)
roscoe dillon (42)
hartley rathaway (249)
flashpoint leonard snart (1)
flashpoint digger harkness (1)
flashpoint hartley rathaway (1)
other5 (2)
film: justice league: the flashpoint paradox (3)
icons (73)
lotedit (78)
lotsource (36)
mickroryedit (63)
raypalmeredit (3)
saralanceedit (8)
sara lance (149)
ray palmer (118)
axl the rat (12)
mark mardon (177)
evan mcculloch (60)
pairing: coldatom (40)
lot 3x13 (4)
c: final crisis: rogues revenge (6)
lot 3x08 (37)
crisis on earth x (88)
the flash 1x10 (57)
the flash 2x17 (22)
preboot (298)
lot 2x08 (48)
lot 2x17 (47)
legion leonard snart (92)
corrections (9)
pairing: mindtrix (3)
lot 3x03 (28)
pairing: canarywave (61)
lot 1x04 (44)
lot 1x05 (72)
samscudderedit (8)
mirror master (2)
comic (1)
the flash 1x17 (6)
fam: tricksters (5)
lisasnartedit (8)
axelwalkeredit (12)
the flash 4x11 (15)
tagged (37)
lot 3x07 (24)
the flash 4x13 (5)
amunet black (49)
the flash spoilers (67)
deleted scene (9)
lot 2x06 (17)
fam: snarts (62)
lot 1x12 (52)
dctvedit (9)
roy bivolo (41)
flashing / (91)
the flash 1x07 (2)
tony woodward (12)
tony woodward death / (1)
tobacco / (7)
the flash 4x08 (45)
lot 1x03 (40)
c: the flash v3 (39)
edward teach (1)
amayajiweedit (2)
amaya jiwe (63)
owen mercer (13)
others (11)
amunetblackedit (9)
the flash 4x05 (18)
the flash 4x09 (16)
c: suicide squad v5 (38)
rebirth (111)
lot 2x04 (23)
shawna baez (109)
the flash 2x03 (109)
abuse / (18)
young mick rory (27)
lot 1x02 (48)
trio: peekatopgold (4)
cast (71)
andy mientus (3)
baoaedit (1)
diggerharknessedit (8)
film: batman: assault on arkham (2)
superhero fight club (8)
trio: rogue canary (29)
evanmccullochedit (1)
c: animal man v1 (4)
lot 1x10 (33)
pairing: coldnews (13)
the flash 2x09 (64)
the flash 1x22 (90)
lot 1x01 (69)
admin (15)
promo (5)
stills (4)
resources (6)
the flash 1x11 (28)
tv: justice league unlimited (5)
the flash 4x01 (15)
zaritomazedit (1)
zari tomaz (3)
the flash 1x16 (70)
pairing: pipster (7)
joey monteleone (7)
pda / (29)
pairing: liscoe (11)
nateheywoodedit (2)
leonardsnartedit (47)
nate heywood (30)
lot 2x12 (5)
pairing: jamoey (1)
zoey clark (2)
pairing: boomshot (10)
jake simmons (4)
fic (10)
c: suicide squad most wanted: deadshot and katana (1)
peyton list (4)
*promos (37)
lot 2x03 (23)
barryallenedit (18)
kylenimbusedit (1)
kyle nimbus (16)
barry allen (210)
the flash 1x03 (6)
pairing: goldentop (2)
c: batman v1 (2)
crack (31)
albert desmond (46)
c: justice league unlimited (2)
dominic purcell (24)
*stills (18)
julian albert (13)
pairing: killergold (10)
trio: supercoldflash (2)
lot 2x16 (69)
marco mardon (79)
jefferson jackson (7)
renegades (18)
hunk norvock (1)
frances kane (11)
pairing: mirrorang (5)
tv: supergirl (15)
pairing: livecold (2)
pairing: goldenvibe (69)
gorilla grodd (20)
the flash 3x22 (151)
solicitations (10)
trio: golden coldwave (16)
wentworth miller (18)
the flash 4x12 (2)
the flash 1x15 (12)
c: injustice 2 (6)
gregory wolfe (1)
theflashdaily (12)
pairing: reversecold (5)
spoilers (1)
corinne bohrer (1)
devon graye (2)
lot 1x09 (24)
c: injustice: year five (6)
eobard thawne (31)
piaring: reversecold (1)
film: justice league (1)
trio: goldenfrostsiren (2)
fam: rorys (12)
text post meme (36)
trio: coldflashwave (9)
arrowedit (6)
dctvpoc (5)
tv: arrow (44)
arrow 3x08 (5)
pairing: snartness (2)
ray terrill (13)
tv: challenge of the super friends (1)
the flash 2x01 (5)
pairing: coldflashwave (3)
dream leonard snart (3)
dream mick rory (3)
pairing: mirrortop (12)
pairing: superwave (9)
citizen abra (21)
pairing: weathster (3)
pairing: heatvibe (7)
theflashgifs (3)
flashallens (3)
pairing: barraxel (4)
injustice 2 (17)
games (19)
lisa snart death / (2)
vg: injustice 2 (17)
pairing: coldstein (5)
lot 2x07 (23)
pairing: steelwave (26)
lot 3x09 (32)
pairing: goldenboo (6)
young leonard snart (12)
lot 1x14 (28)
*icons (11)
film: suicide squad (64)
pairing: wallboom (6)
c: batman and harley quinn (1)
pairing: quinnarang (10)
mick rory death / (3)
marco mardon death / (1)
film: suicide squad: hell to pay (1)
sshtpedit (1)
film (1)
pairing: hawkwave (7)
kendra saunders (2)
trio: coldwestallen (12)
pairing: hackness (3)
fashion (14)
pairing: canaryfire (2)
pairing: flashwave (2)
pairing: blackfrost (19)
lot 3x02 (15)
lily stein (2)
pairing: lilywave (4)
pairing: blackice (1)
tatsu yamashiro (1)
pairing: katanarang (6)
*panels (180)
pairing: flasharang (8)
queensarrow (1)
tv: justice league action (4)
jla 1x41 (2)
pairing: snartaway (4)
hallucination leonard snart (25)
martin stein (2)
pairing: steinwave (11)
pairing: pipebomb (2)
trio: coldatomwave (9)
michael amar (6)
c: the flash: iron heights (5)
ray palmer death / (2)
lot 3x01 (19)
martin stein death / (1)
the flash 2x07 (1)
harley quinn (4)
cisco ramon (107)
supergirl 3x08 (13)
pairing: cold archer (2)
malcolm merlyn (5)
lot 2x11 (25)
grant gustin (8)
c: dc rebirth holiday special (8)
v? (33)
markmardonedit (6)
pairing: coldweather (11)
trio: coldtrickweather (3)
arrow 6x08 (6)
pairing: killerwave (8)
pairing: coldarrow (3)
nazi / (3)
caitlinsnowedit (4)
ciscoramonedit (4)
harrisonwellsedit (2)
caitlin snow (25)
harrison wells (2)
*rm (6)
rm:tony (3)
lot 2x13 (9)
trio: coldvixenwave (8)
wednesday spoilers (7)
cassandra savage (1)
pairing: cassnart (3)
lot 1x13 (26)
pairing: singaway (19)
pairing: hartmon (35)
eleanor darhk (1)
lot 3x06 (4)
pairing: stormwave (5)
jared morillo (6)
requests (10)
arrow 4x03 (6)
jeremy tell (10)
jaxedit (5)
martinsteinedit (1)
c: suicide squad v1 (2)
the flash 3x03 (11)
frankie kane (24)
the flash 1x01 (8)
clyde mardon (15)
lot 3x04 (15)
lot 1x07 (53)
mindy hong (2)
theflashcastedit (2)
womensleague (1)
dailydcqueens (1)
wonderfulwoc (1)
boldfordedit (1)
britne oldford (3)
nazi imagery / (6)
lot 1x08 (24)
speedforce leonard snart (12)
jla 0x14 (1)
supergirl spoilers (5)
coldwaveedit (3)
pairing: weatherpiper (5)
oliver queen (5)
lot 2x01 (15)
fancast (3)
wally west (10)
pairing: mickster (5)
c: flashpoint v2 (1)
c: justice league v2 (8)
pamela isley (1)
c: forever evil: rogues rebellion (26)
pairing: poister (1)
arrow spoilers (9)
c: the flash: season zero (3)
eddiethawneedit (2)
david singh (1)
eddie thawne (3)
joe west (6)
the flash 1x06 (3)
canxary (1)
katee sackhoff (3)
pairing: weathertop (1)
danielle panabaker (4)
the flash 4x04 (2)
dailymickrory (6)
pairing: trickaboo (1)
dick rory (1)
pairing: quicktrick (1)
jesse wells (1)
the flash 1x08 (1)
eye horror / (12)
fandom weeks (7)
lot 305 (1)
flash rogues (3)
dailydcheroes (3)
dcvertigodaily (11)
by armelle (8)
jlu 5x05 (4)
pairing: trickgold (2)
playlist (4)
lot 2x05 (28)
victor fries (1)
the flash 2x12 (1)
chronos mick rory (1)
lot sp (1)
shawnabaezedit (11)
by abby (11)
video (8)
uncaptioned video (6)
described video (1)
*video (1)
autoplay / (1)
lashawn baez (6)
pairing: peekatop (1)
the flash 1x12 (30)
heatwave (1)
gifs (1)
riphunteredit (1)
rip hunter (1)
captain cold (7)
ep? (9)
c: salvation run (6)
nick zano (1)
reading list (4)
pairing: hartlian (1)
edward nygma (1)
c: robin v4 (2)
undescribed video (6)
gary green (1)
pairing: goldflash (8)
captain boomerang (1)
tv: young justice (6)
tv: batman: the brave and the bold (1)
meme (19)
amanda waller (4)
c: suicide squad v4 (10)
pairing: goldenalchemy (1)
pairing: peekavibe (5)
august heart (2)
bart allen (1)
c: teen titans v3 (1)
signal boost (5)
golden glider (1)
tim drake (1)
gideon (1)
floyd lawton (9)
pairing: plastiqueboo (3)
claudio mardon (1)
fam: mardons (7)
clay parker (1)
c: catwoman v3 (12)
selina kyle (10)
pairing: coldcat (10)
c: final crisis (2)
first look trailer (1)
pairing: coldcanary (1)
baby leonard snart (7)
lot 2x15 (46)
rm:lisa (1)
joewestedit (3)
felicity smoak (2)
rm:leonard (1)
rm:clyde (3)
rm:kyle (2)
film: justice league vs teen titans (1)
trio: quinnshotarang (4)
the flash (119)
amaya jiwe death / (4)
c: red hood and the outlaws v2 (1)
legends of tomorrow bloopers (8)
brandon routh (3)
caity lotz (3)
arthur darvill (1)
ciara renee (2)
jay garrick (3)
last reminder (1)
the flash 3x08 (10)
victor garber (2)
arrow 3x01 (1)
arrow 3x17 (1)
the flash 1x20 (2)
lot 2x10 (8)
c: gotham central (8)
pairing: arrowwave (6)
pairing: goldennews (5)
elsa mardon (2)
pairing: coldstorm (10)
pairing: hellwave (2)
theroguesedit (2)
arrow 5x23 (15)
echo kellum (2)
stephen amell (1)
emily bett rickards (2)
katrina law (4)
willa holland (1)
madison mclaughlin (1)
anna hopkins (1)
nick tarabay (5)
curtis holt (1)
nyssa al ghul (4)
thea queen (1)
evelyn sharpe (1)
samantha clayton (1)
pairing: coldmirror (8)
pairing: tidalwave (2)
alvin desmond (17)
film: justice league: doom (1)
ezra miller (1)
jai courtney (2)
liam mcintyre (5)
mark hamill (3)
kevin tancharoen (1)
c kim miles (1)
dailydcgifs (5)
kyle rayner (1)
trio: goldenlovebirds (1)
pairing: westaway (6)
linda park (2)
pairing: coldtime (8)
chad rook (2)
c: general mills presents: justice league (1)
audism / (8)
trio: peekagoldennews (1)
chronicles of cisco (5)
hologram leonard snart (6)
pairing: wavetime (13)
lotcastedit (2)
dpurcelledit (1)
dailydccast (1)
trio: goldlightbow (1)
detcorrigan (2)
trio: bartlian (1)
pairing: flashweather (10)
trio: stormfrostweather (1)
coldflashedit (1)
the flash 3x16 (13)
trio: flashviper (1)
pairing: whitegold (4)
pairing: goldweather (3)
clydemardonedit (3)
darren criss (1)
music meister (1)
trio: oliciwave (1)
trio: kidtrickpiper (1)
damien darhk (2)
carlos valdes (6)
pairing: golden canary (6)
trio: coldhawkwave (1)
pairing: animirror (3)
pairing: topiper (1)
the flash 3x02 (2)
trio: smoaking goldennews (1)
pairing: greenweather (1)
pairing: detectivegold (2)
c: secret origins v2 (1)
pairing: flashpiper (8)
pairing: detectivegold (1)
pairing: goldmirror (7)
pairing: trickweather (3)
c: injustice: gods among us (2)
trio: greenflashweather (1)
c: tiny titans (1)
jesse l martin (1)
joey king (2)
keiynan lonsdale (3)
suicide squad (14)
rm:rosa (1)
lot 2x09 (3)
pairing: peekafrost (1)
injustice (7)
arrowcastedit (1)
franz drameh (2)
maisie richardson sellers (1)
sdcc 2017 (1)
grey damon (3)
chillblaine (3)
showcase (4)
c: showcase v1 (5)
rogues rebellion (9)
trio: goldenblackvibe (1)
the flash 1x19 (1)
pairing: vosnart (3)
pairing: cassandrory (3)
trio: goldenwestwave (1)
the flash 2x21 (2)
pairing: canaryboo (1)
trio: vixensteelwave (3)
the flash 1x23 (2)
c: blackest night: the flash (1)
yj 2x08 (3)
vg: dc legends (1)
pairing: speedyglider (1)
pairing: torrainbow (3)
john barrowman (2)
the flash 3x18 (10)
david dastmalchian (1)
jessica camacho (1)
cynthia reynolds (2)
the flash 1x02 (1)
trio: peekagoldenfrost (1)
animal man (1)
pairing: overwave (3)
pairing: weatherboo (2)
dailyflarrowgifs (4)
pairing: mickington (2)
gun / (1)
lot 2x02 (6)
trio: parkwestaway (1)
pairing: shawndra (1)
arrow 3x23 (1)
clive yorkin (1)
edward clariss (1)
animal cruelty / (1)
the flash 3x07 (2)
suicide / (1)
arrow 3x19 (1)
the flash 3x23 (1)
c: dc: the new frontier (1)
pairing: coldvibe (7)
trio: wizardhawkmates (1)
pairing: mirrorwave (3)
trio: stormfrostwave (1)
pairing: boomflag (2)
pairing: parksnart (1)
jla incarnations (1)
c: jla incarnations (1)
the flash 1x13 (1)
pairing: rathawne (1)
lilysteinedit (1)
rm:mark (1)
the flash 3x11 (1)
c: gotham underground (1)
warren white (1)
c: final crisis: rogues revenge (1)
throwawaytheplan (1)
yj 1x01 (2)
pairing: piedler (1)
trio: supercanarywave (2)
salvation run (2)
iriswestedit (2)
iris west (2)
the flash 2x08 (1)
trio: coldvibewave (1)
thefortunatesons (3)
captioned gifset (1)
yjedit (1)
gotham central (1)
justice league (7)
injustice2edit (5)
jluedit (3)
justice league vs suicide squad (2)
c: justice league vs. suicide squad (2)
oliverqueenedit (2)
pairing: wondercold (3)
captaincoldedit (4)
pairing: flashmirror (7)
goldenvibeedit (1)
the flash 3x17 (2)
injustice ground zero (1)
c: injustice: ground zero (1)
the flash 3x14 (1)
royharperedit (1)
roy harper (1)
pairing: barosa (5)
killer frost (1)
the flash 3x20 (1)
tv: vixen (2)
pairing: flaming boomerang (3)
proud of this one I am! (1)
suicide squad most wanted (1)
the flash: iron heights (1)
isaac bowin (1)
titans (2)
c: titans v3 (2)
roybivoloedit (1)
trio: goldtorrainbow (1)
christmas special (1)
event (3)
yes yes i know i am not dead :) (1)
the new teen titans (1)
c: the new teen titans v1 (1)
pairing: boomster (1)
identity crisis (1)
c: identity crisis (1)
ashley rickards (1)
pairing: mirrorweather (1)
pairing: trickmirror (1)
pairing: goldpiper (1)
suicidal / (1)
catwoman (1)
the flash 3x01 (1)
lot 2x14 (2)
c: new suicide squad v1 (1)
pairing: boomerknot (1)
c: 52 (1)
homophobia (1)
pairing: superang (1)
c: suicide squad: war crimes special (1)
the flash bloopers (1)
pairing: flashaboo (1)
pairing: powerang (1)
hunter zolomon (1)
sorry for the shitty quality (1)
pairing: goldwave (1)
vixen s2 (1)
"""


tagssep = taglist.split("/n")




